DROP TABLE SHELTER;
-- 회원테이블
CREATE TABLE SHELTER(
    SID     NVARCHAR2(10) PRIMARY KEY,
    SPW     NVARCHAR2(10) NOT NULL,
    SNAME   NVARCHAR2(5) NOT NULL,
    SADDR   NVARCHAR2(30),
    SPHONE  NVARCHAR2(15) NOT NULL,
    SEMAIL  NVARCHAR2(30),
    SCHAR   NVARCHAR2(1),
    CMONNEY NVARCHAR2(20)
);

DROP TABLE DOG;
-- 유기견테이블
CREATE TABLE DOG(
    DNO     NUMBER(38) PRIMARY KEY,
    DNAME   NVARCHAR2(10) not null,
    DAGE    NUMBER(3),
    DBREED  NVARCHAR2(10),
    DSEX    NVARCHAR2(2),
    DREGITDATE  DATE
);

DROP SEQUENCE DOG_SQ;
-- 공고번호 자동생성을 위한 시퀀스 생성
CREATE SEQUENCE DOG_SQ
INCREMENT BY 1
START WITH 1
MAXVALUE 1000
MINVALUE 1
NOCYCLE
NOCACHE;

COMMIT;